### ISSUE TITLE
Unable to login to Osclass application

### ISSUE THREAD

**Issue by sameersbn** [bitnami/bitnami-docker-osclass#6]
I deployed the application using the following `docker-compose.yml` file. But i was not able to login to the application using the credentials `user@example.com` / `bitnami1`. Specifying custom credentials using the `OSCLASS_{USERNAME, PASSWORD, EMAIL}` parameters do not help.

```yaml
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  application:
    image: 'bitnami/osclass:latest'
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - mariadb
    volumes:
      - 'osclass_data:/bitnami/osclass'
      - 'apache_data:/bitnami/apache'
volumes:
  mariadb_data:
    driver: local
  osclass_data:
    driver: local
  apache_data:
    driver: local
```
